default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  username: YOUR_USERNAME_HERE
  password: YOUR_PASSWORD_HERE

development:
  <<: *default
  database: demo_blog_development

test:
  <<: *default
  database: demo_blog_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
