default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: YOUR_USERNAME_HERE
  password: YOUR_PASSWORD_HERE
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: demo_blog_development

test:
  <<: *default
  database: demo_blog_test
